[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "snowflake.driver"
version = "2.6.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Business Intelligence/Data Warehouse", "Cost/Paid"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-snowflake.driver"

[build-options]
observabilityIncluded = true

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "net.snowflake"
artifactId = "snowflake-jdbc"
version = "3.13.11"
